import { getAuth } from "@/lib/auth/auth";
import { ensurePersonalWorkspace } from "@/lib/auth/workspace";
import { getPrisma } from "@/lib/db/prisma";

export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const session = await getAuth().api.getSession({ headers: request.headers });
  if (!session)
    return Response.json(
      { error: "Unauthorized" },
      { status: 401, headers: { "Cache-Control": "private, no-store" } },
    );
  const workspace = await ensurePersonalWorkspace(session.user);
  const prisma = getPrisma();
  const owned = await prisma.workspace.findUnique({
    where: { id: workspace.id },
    include: {
      installations: true,
      trackedRepositories: {
        include: {
          snapshot: true,
          evidence: { include: { observations: true } },
          syncRuns: true,
          ingestionJobs: true,
          webhookDeliveries: true,
        },
      },
      evidenceClaims: {
        include: {
          evidenceLinks: true,
          revisions: true,
          sourceCandidate: { select: { id: true, requestId: true } },
        },
      },
      draftingConsents: true,
      draftGenerationRequests: {
        include: {
          ingestionJob: {
            select: { attemptCount: true, maximumAttempts: true },
          },
          evidenceSelections: { orderBy: { position: "asc" } },
          candidate: {
            include: {
              sentences: {
                orderBy: { position: "asc" },
                include: {
                  citations: { orderBy: { position: "asc" } },
                },
              },
            },
          },
        },
      },
      draftReviewEvents: true,
      publicProfile: true,
      projectPublications: {
        include: {
          claimSelections: {
            orderBy: { position: "asc" },
            include: {
              evidenceDisclosures: { orderBy: { position: "asc" } },
            },
          },
          revisions: {
            orderBy: { revisionNumber: "asc" },
            include: {
              claimSnapshots: {
                orderBy: { position: "asc" },
                include: {
                  evidenceSnapshots: { orderBy: { position: "asc" } },
                },
              },
            },
          },
          events: { orderBy: { createdAt: "asc" } },
        },
      },
      portfolioOutputs: {
        include: {
          claimSelections: { orderBy: { position: "asc" } },
          revisions: { orderBy: { revisionNumber: "asc" } },
        },
      },
      auditEvents: true,
    },
  });
  await prisma.auditEvent.create({
    data: {
      workspaceId: workspace.id,
      userId: session.user.id,
      type: "account.export.requested",
    },
  });
  const exportData = {
    version: 4,
    exportedAt: new Date().toISOString(),
    account: { id: session.user.id, email: session.user.email },
    workspace: owned && {
      id: owned.id,
      name: owned.name,
      createdAt: owned.createdAt,
      installations: owned.installations.map(
        ({
          installationId,
          accountId,
          accountLogin,
          accountType,
          repositorySelection,
          permissions,
          verifiedAt,
          lastRepositoryDiscoveryAt,
        }) => ({
          installationId: installationId.toString(),
          accountId: accountId.toString(),
          accountLogin,
          accountType,
          repositorySelection,
          permissions,
          verifiedAt,
          lastRepositoryDiscoveryAt,
        }),
      ),
      trackedRepositories: owned.trackedRepositories.map((repository) => ({
        id: repository.id,
        githubRepositoryId: repository.githubRepositoryId.toString(),
        fullName: repository.fullName,
        visibility: repository.visibility,
        snapshot: repository.snapshot?.normalizedData ?? null,
        evidence: repository.evidence.map(
          ({
            evidenceId,
            evidenceType,
            githubSourceId,
            canonicalUrl,
            occurredAt,
            title,
            sourceLabel,
            confidence,
            factualPayload,
            normalizedContentHash,
            sourceAvailability,
            sourceUnavailableAt,
            firstSeenAt,
            lastSeenAt,
            observations,
          }) => ({
            evidenceId,
            evidenceType,
            githubSourceId,
            canonicalUrl,
            occurredAt,
            title,
            sourceLabel,
            confidence,
            factualPayload,
            normalizedContentHash,
            sourceAvailability,
            sourceUnavailableAt,
            firstSeenAt,
            lastSeenAt,
            observations: observations.map(
              ({
                sourceKind,
                syncRunId,
                webhookDeliveryId,
                observedAt,
                normalizedContentHash: observationHash,
                createdAt,
              }) => ({
                sourceKind,
                syncRunId,
                webhookDeliveryId,
                observedAt,
                normalizedContentHash: observationHash,
                createdAt,
              }),
            ),
          }),
        ),
        syncRuns: repository.syncRuns.map(
          ({
            mode,
            status,
            startedAt,
            completedAt,
            sanitizedErrorCode,
            insertedCount,
            updatedCount,
            seenCount,
            sectionAvailability,
          }) => ({
            mode,
            status,
            startedAt,
            completedAt,
            sanitizedErrorCode,
            insertedCount,
            updatedCount,
            seenCount,
            sectionAvailability,
          }),
        ),
        webhookDeliveries: repository.webhookDeliveries.map(
          ({
            githubDeliveryId,
            eventName,
            action,
            payloadSha256,
            bodyByteCount,
            duplicateCount,
            receivedAt,
            status,
            ignoredReason,
            processedAt,
            sanitizedErrorCode,
          }) => ({
            githubDeliveryId,
            eventName,
            action,
            payloadSha256,
            bodyByteCount,
            duplicateCount,
            receivedAt,
            status,
            ignoredReason,
            processedAt,
            sanitizedErrorCode,
          }),
        ),
        ingestionJobs: repository.ingestionJobs.map(
          ({
            id,
            kind,
            status,
            availableAt,
            attemptCount,
            maximumAttempts,
            startedAt,
            completedAt,
            sanitizedLastErrorCode,
            createdAt,
          }) => ({
            id,
            kind,
            status,
            availableAt,
            attemptCount,
            maximumAttempts,
            startedAt,
            completedAt,
            sanitizedLastErrorCode,
            createdAt,
          }),
        ),
      })),
      claims: owned.evidenceClaims.map(
        ({
          id,
          trackedRepositoryId,
          statement,
          status,
          origin,
          humanEditedAfterAcceptance,
          verifiedAt,
          version,
          createdAt,
          updatedAt,
          evidenceLinks,
          revisions,
          sourceCandidate,
        }) => ({
          id,
          trackedRepositoryId,
          statement,
          status,
          origin,
          humanEditedAfterAcceptance,
          verifiedAt,
          version,
          createdAt,
          updatedAt,
          evidenceLinks: evidenceLinks.map(
            ({ repositoryEvidenceId, createdAt: linkedAt }) => ({
              repositoryEvidenceId,
              linkedAt,
            }),
          ),
          revisions: revisions.map(
            ({
              revisionNumber,
              kind,
              statementSnapshot,
              status: revisionStatus,
              evidenceIdSnapshot,
              changeSummary,
              createdAt: revisedAt,
            }) => ({
              revisionNumber,
              kind,
              statementSnapshot,
              status: revisionStatus,
              evidenceIdSnapshot,
              changeSummary,
              revisedAt,
            }),
          ),
          acceptedCandidate: sourceCandidate && {
            id: sourceCandidate.id,
            draftRequestId: sourceCandidate.requestId,
          },
        }),
      ),
      draftingConsents: owned.draftingConsents.map(
        ({
          id,
          consentVersion,
          privacyPolicyVersion,
          providerKind,
          providerClassification,
          providerIdentityHash,
          acceptedByUserId,
          acceptedAt,
          revokedAt,
          createdAt,
          updatedAt,
        }) => ({
          id,
          consentVersion,
          privacyPolicyVersion,
          providerKind,
          providerClassification,
          providerIdentityHash,
          acceptedByUserId,
          acceptedAt,
          revokedAt,
          createdAt,
          updatedAt,
        }),
      ),
      draftGenerationRequests: owned.draftGenerationRequests.map(
        ({
          id,
          trackedRepositoryId,
          regenerationOfId,
          providerKind,
          providerClassification,
          providerIdentityHash,
          modelLabel,
          promptTemplateVersion,
          evidenceBundleVersion,
          evidenceBundleHash,
          draftingIntent,
          style,
          status,
          requestHash,
          queuedAt,
          startedAt,
          completedAt,
          sanitizedErrorCode,
          inputEvidenceCount,
          inputByteCount,
          outputByteCount,
          requestDurationMs,
          inputTokenCount,
          outputTokenCount,
          createdAt,
          updatedAt,
          ingestionJob,
          evidenceSelections,
          candidate,
        }) => ({
          id,
          trackedRepositoryId,
          regenerationOfId,
          providerKind,
          providerClassification,
          providerIdentityHash,
          modelLabel,
          promptTemplateVersion,
          evidenceBundleVersion,
          evidenceBundleHash,
          draftingIntent,
          style,
          status,
          requestHash,
          queuedAt,
          startedAt,
          completedAt,
          sanitizedErrorCode,
          usage: {
            inputEvidenceCount,
            inputByteCount,
            outputByteCount,
            requestDurationMs,
            inputTokenCount,
            outputTokenCount,
            attemptCount: ingestionJob?.attemptCount ?? 0,
            retryCount: Math.max((ingestionJob?.attemptCount ?? 0) - 1, 0),
            maximumAttempts: ingestionJob?.maximumAttempts ?? null,
          },
          createdAt,
          updatedAt,
          evidenceSelections: evidenceSelections.map(
            ({
              repositoryEvidenceId,
              evidenceContentHash,
              position,
              createdAt: selectedAt,
            }) => ({
              repositoryEvidenceId,
              evidenceContentHash,
              position,
              selectedAt,
            }),
          ),
          candidate: candidate && {
            id: candidate.id,
            candidateVersion: candidate.candidateVersion,
            title: candidate.title,
            combinedStatement: candidate.combinedStatement,
            caveats: candidate.caveats,
            policyWarnings: candidate.policyWarnings,
            confidence: candidate.confidence,
            groundingStatus: candidate.groundingStatus,
            reviewStatus: candidate.reviewStatus,
            acceptedClaimId: candidate.acceptedClaimId,
            acceptedAt: candidate.acceptedAt,
            rejectedAt: candidate.rejectedAt,
            rejectionReason: candidate.rejectionReason,
            coverage: {
              sentenceCount: candidate.sentenceCount,
              citedSentenceCount: candidate.citedSentenceCount,
              uniqueEvidenceCount: candidate.uniqueEvidenceCount,
              selectedEvidenceCount: candidate.selectedEvidenceCount,
              evidenceTypesUsed: candidate.evidenceTypesUsed,
              unusedSelectedEvidenceCount:
                candidate.unusedSelectedEvidenceCount,
            },
            sentences: candidate.sentences.map((sentence) => ({
              position: sentence.position,
              text: sentence.text,
              citations: sentence.citations.map((citation) => ({
                repositoryEvidenceId: citation.repositoryEvidenceId,
                position: citation.position,
              })),
            })),
            createdAt: candidate.createdAt,
          },
        }),
      ),
      draftReviewEvents: owned.draftReviewEvents.map(
        ({
          draftRequestId,
          candidateId,
          claimId,
          actorUserId,
          kind,
          metadata,
          createdAt,
        }) => ({
          draftRequestId,
          candidateId,
          claimId,
          actorUserId,
          kind,
          metadata,
          createdAt,
        }),
      ),
      publicProfile: owned.publicProfile && {
        slug: owned.publicProfile.slug,
        displayName: owned.publicProfile.displayName,
        headline: owned.publicProfile.headline,
        biography: owned.publicProfile.biography,
        locationText: owned.publicProfile.locationText,
        personalWebsiteUrl: owned.publicProfile.personalWebsiteUrl,
        githubProfileUrl: owned.publicProfile.githubProfileUrl,
        visibility: owned.publicProfile.visibility,
        firstPublishedAt: owned.publicProfile.firstPublishedAt,
        latestPublishedAt: owned.publicProfile.latestPublishedAt,
        version: owned.publicProfile.version,
        createdAt: owned.publicProfile.createdAt,
        updatedAt: owned.publicProfile.updatedAt,
      },
      projectPublications: owned.projectPublications.map((publication) => ({
        id: publication.id,
        trackedRepositoryId: publication.trackedRepositoryId,
        slug: publication.slug,
        internalTitle: publication.internalTitle,
        status: publication.status,
        visibility: publication.visibility,
        draft: {
          title: publication.title,
          summary: publication.summary,
          roleText: publication.roleText,
          projectPeriodText: publication.projectPeriodText,
          technologyLabels: publication.technologyLabels,
          problemText: publication.problemText,
          approachText: publication.approachText,
          outcomeText: publication.outcomeText,
          repositoryDisclosurePolicy: publication.repositoryDisclosurePolicy,
        },
        currentPublishedRevisionId: publication.currentPublishedRevisionId,
        firstPublishedAt: publication.firstPublishedAt,
        latestPublishedAt: publication.latestPublishedAt,
        unpublishedAt: publication.unpublishedAt,
        archivedAt: publication.archivedAt,
        health: {
          state: publication.healthState,
          checkedAt: publication.healthCheckedAt,
        },
        version: publication.version,
        createdAt: publication.createdAt,
        updatedAt: publication.updatedAt,
        claimSelections: publication.claimSelections.map((selection) => ({
          claimId: selection.claimId,
          position: selection.position,
          selectedStatementHash: selection.selectedStatementHash,
          evidenceDisclosures: selection.evidenceDisclosures.map(
            (disclosure) => ({
              repositoryEvidenceId: disclosure.repositoryEvidenceId,
              position: disclosure.position,
              mode: disclosure.mode,
              publicTitle: disclosure.publicTitle,
              includeOccurredAt: disclosure.includeOccurredAt,
              sourceContentHash: disclosure.sourceContentHash,
            }),
          ),
        })),
        revisions: publication.revisions.map((revision) => ({
          id: revision.id,
          revisionNumber: revision.revisionNumber,
          title: revision.title,
          summary: revision.summary,
          roleText: revision.roleText,
          projectPeriodText: revision.projectPeriodText,
          technologyLabels: revision.technologyLabels,
          problemText: revision.problemText,
          approachText: revision.approachText,
          outcomeText: revision.outcomeText,
          repositoryDisclosurePolicy: revision.repositoryDisclosurePolicy,
          publicRepositoryLabel: revision.publicRepositoryLabel,
          publicRepositoryUrl: revision.publicRepositoryUrl,
          authorSnapshot: {
            slug: revision.authorSlug,
            displayName: revision.authorDisplayName,
            headline: revision.authorHeadline,
            biography: revision.authorBiography,
            locationText: revision.authorLocationText,
            personalWebsiteUrl: revision.authorPersonalWebsiteUrl,
            githubProfileUrl: revision.authorGithubProfileUrl,
          },
          visibility: revision.visibility,
          publishedAt: revision.publishedAt,
          contentHash: revision.contentHash,
          schemaVersion: revision.schemaVersion,
          supersededAt: revision.supersededAt,
          claimSnapshots: revision.claimSnapshots.map((claim) => ({
            sourceClaimId: claim.sourceClaimId,
            publicClaimIdentifier: claim.publicClaimIdentifier,
            position: claim.position,
            statement: claim.statement,
            statementHash: claim.statementHash,
            claimOrigin: claim.claimOrigin,
            verifiedAt: claim.verifiedAt,
            humanEdited: claim.humanEdited,
            evidenceSnapshots: claim.evidenceSnapshots.map((evidence) => ({
              sourceRepositoryEvidenceId: evidence.sourceRepositoryEvidenceId,
              publicDisclosureIdentifier: evidence.publicDisclosureIdentifier,
              position: evidence.position,
              evidenceType: evidence.evidenceType,
              publicTitle: evidence.publicTitle,
              occurredAt: evidence.occurredAt,
              disclosureMode: evidence.disclosureMode,
              canonicalPublicSourceUrl: evidence.canonicalPublicSourceUrl,
              sourceVisibility: evidence.sourceVisibility,
              publicProvenanceText: evidence.publicProvenanceText,
              confidence: evidence.confidence,
              sourceContentHash: evidence.sourceContentHash,
              contentHash: evidence.contentHash,
            })),
          })),
        })),
        events: publication.events.map((event) => ({
          kind: event.kind,
          safeMetadata: event.safeMetadata,
          createdAt: event.createdAt,
        })),
      })),
      portfolioOutputs: owned.portfolioOutputs.map((output) => ({
        id: output.id,
        trackedRepositoryId: output.trackedRepositoryId,
        type: output.type,
        title: output.title,
        status: output.status,
        draftFields: output.draftFields,
        currentRevisionId: output.currentRevisionId,
        archivedAt: output.archivedAt,
        version: output.version,
        createdAt: output.createdAt,
        updatedAt: output.updatedAt,
        claimSelections: output.claimSelections.map((selection) => ({
          claimId: selection.claimId,
          position: selection.position,
          statementOverride: selection.statementOverride,
        })),
        revisions: output.revisions.map((revision) => ({
          revisionNumber: revision.revisionNumber,
          templateVersion: revision.templateVersion,
          claimSnapshots: revision.claimSnapshots,
          userFields: revision.userFields,
          structuredContent: revision.structuredContent,
          renderedText: revision.renderedText,
          renderedMarkdown: revision.renderedMarkdown,
          contentHash: revision.contentHash,
          createdAt: revision.createdAt,
        })),
      })),
      auditEvents: owned.auditEvents.map(({ type, metadata, createdAt }) => ({
        type,
        metadata,
        createdAt,
      })),
    },
  };
  return new Response(JSON.stringify(exportData, null, 2), {
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Content-Disposition": 'attachment; filename="committrail-export.json"',
      "Cache-Control": "private, no-store",
      "X-Content-Type-Options": "nosniff",
    },
  });
}
